"""add is_deleted to expenses

Revision ID: 0c648ff1f17b
Revises: 239faaa0f47b
Create Date: 2025-12-27 11:34:30.270118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c648ff1f17b'
down_revision: Union[str, Sequence[str], None] = '239faaa0f47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_deleted')
    # ### end Alembic commands ###
