"""fix column name in expense

Revision ID: 9201f62242e0
Revises: 9343f7aafa8d
Create Date: 2025-11-20 11:40:54.988270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9201f62242e0'
down_revision: Union[str, Sequence[str], None] = '9343f7aafa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('expenses', 'amout')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amout', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'amount')
    # ### end Alembic commands ###
